use("test")

// if specified, clear out all existing collections (except the users collection)
if (true) {
   db.volunteers.deleteMany({})
   db.organizations.deleteMany({})
   db.eventVolunteers.deleteMany({})
   db.events.deleteMany({})
}

// create 10 organizationId variables
for (let i = 1; i <= 10; i++) {
  this[`organizationId${i}`] = ObjectId();
}

db.organizations.insertMany([
    {
        "_id": organizationId1,
        "name": "Harmony Haven Outreach",
        "softDelete": true,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId2,
        "name": "Lighthouse Legacy Foundation",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId3,
        "name": "Compassionate Crossroads Mission",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId4,
        "name": "Faithful Friends Collective",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId5,
        "name": "Serenity Springs Community Service",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId6,
        "name": "Graceful Giving Guild",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId7,
        "name": "Benevolent Blessings Brigade",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId8,
        "name": "Charity's Chosen Circle",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId9,
        "name": "Pathways of Promise Partnership",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": organizationId10,
        "name": "Divine Deeds Coalition",
        "softDelete": false,
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
])

// creates 31 volunteerId variables
for (let i = 1; i <= 31; i++) {
  this[`volunteerId${i}`] = ObjectId();
}

db.volunteers.insertMany([
{
    "_id": volunteerId1,
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "phoneNumber": "1234567890",
    "address": "123 Main St, Anytown, USA",
    "previousRole": "Medical",
    "previousOrganization": organizationId1,
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-30T14:15:22Z"
    },
    "roleVerifications": [
      {
        "verifier": "Emily Parker",
        "lastUpdated": "2023-04-29T10:00:00Z",
        "role": "Medical"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId2,
    "firstName": "Jane",
    "lastName": "Smith",
    "email": "jane.smith@example.com",
    "phoneNumber": "2345678901",
    "address": "456 Elm St, Sometown, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId2,
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-04-29T09:30:00Z"
    },
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId3,
    "firstName": "Alice",
    "lastName": "Johnson",
    "email": "alice.johnson@example.com",
    "phoneNumber": "3456789012",
    "address": "789 Oak St, Anycity, USA",
    "backgroundCheck": {
      "status": "Failed",
      "lastUpdated": "2023-04-15T17:45:30Z"
    },
    "roleVerifications": [],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId4,
    "firstName": "Michael",
    "lastName": "Brown",
    "email": "michael.brown@example.com",
    "phoneNumber": "4567890123",
    "address": "101 Pine St, Mytown, USA",
    "previousRole": "Save the Babies",
    "previousOrganization": organizationId6,
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-20T18:55:00Z"
    },
    "roleVerifications": [
      {
        "verifier": "Michael Johnson",
        "lastUpdated": "2023-04-19T13:33:00Z",
        "role": "Save the Babies"
      },
      {
        "lastUpdated": "2023-04-16T13:33:00Z",
        "role": "Medical"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId5,
    "firstName": "Emily",
    "lastName": "White",
    "email": "emily.white@example.com",
    "phoneNumber": "5678901234",
    "address": "202 Cherry St, Yourtown, USA",
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-22T14:25:47Z"
    },
    "roleVerifications": [
      {
        "verifier": "Olivia Martinez",
        "lastUpdated": "2023-04-21T15:10:00Z",
        "role": "Medical"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId6,
    "firstName": "David",
    "lastName": "Harris",
    "email": "david.harris@example.com",
    "phoneNumber": "6789012345",
    "address": "303 Birch St, Ourtown, USA",
    "previousRole": "Dental",
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-04-18T16:50:35Z"
    },
    "roleVerifications": [
      {
        "verifier": "Ethan Brown",
        "lastUpdated": "2023-04-17T16:00:00Z",
        "role": "Dental"
      }
    ],
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId7,
    "firstName": "Olivia",
    "lastName": "Lewis",
    "email": "olivia.lewis@example.com",
    "phoneNumber": "7890123456",
    "address": "404 Maple St, Webtown, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId4,
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-27T19:00:10Z"
    },
    "roleVerifications": [],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId8,
    "firstName": "Ethan",
    "lastName": "Clark",
    "email": "ethan.clark@example.com",
    "phoneNumber": "8901234567",
    "address": "505 Walnut St, Cloudtown, USA",
    "previousRole": "Save the Babies",
    "previousOrganization": organizationId10,
    "backgroundCheck": {
      "status": "Failed",
      "lastUpdated": "2023-04-05T20:20:20Z"
    },
    "roleVerifications": [
      {
        "verifier": "Ava Rodriguez",
        "lastUpdated": "2023-04-04T18:30:00Z",
        "role": "Save the Babies"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId9,
    "firstName": "Sophia",
    "lastName": "Martinez",
    "email": "sophia.martinez@example.com",
    "phoneNumber": "9012345678",
    "address": "606 Cedar St, Rivertown, USA",
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-04-08T21:10:40Z"
    },
    "roleVerifications": [
      {
        "verifier": "William Smith",
        "lastUpdated": "2023-04-07T19:05:00Z",
        "role": "Medical"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId10,
    "firstName": "Liam",
    "lastName": "Sanchez",
    "email": "liam.sanchez@example.com",
    "phoneNumber": "0123456789",
    "address": "707 Spruce St, Laketown, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId10,
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-11T22:30:00Z"
    },
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId11,
    "firstName": "Charlotte",
    "lastName": "Rodriguez",
    "email": "charlotte.rodriguez@example.com",
    "phoneNumber": "1234509876",
    "address": "808 Palm St, Hilltown, USA",
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-14T23:59:59Z"
    },
    "roleVerifications": [],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId12,
    "firstName": "Isabella",
    "lastName": "Garcia",
    "email": "isabella.garcia@example.com",
    "phoneNumber": "1987654321",
    "address": "909 Willow St, Mountainview, USA",
    "previousRole": "Medical",
    "previousOrganization": organizationId3,
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-03-30T14:15:22Z"
    },
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId13,
    "firstName": "Noah",
    "lastName": "Martinez",
    "email": "noah.martinez@example.com",
    "phoneNumber": "1897654321",
    "address": "1010 Redwood St, Silicon Valley, USA",
    "previousRole": "Dental",
    "previousOrganization": organizationId7,
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-03-29T09:30:00Z"
    },
    "roleVerifications": [
      {
        "verifier": "Sophia Johnson",
        "lastUpdated": "2023-03-25T11:20:00Z",
        "role": "Dental"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId14,
    "firstName": "Mia",
    "lastName": "Lee",
    "email": "mia.lee@example.com",
    "phoneNumber": "1787654321",
    "address": "1111 Pine St, Seaside, USA",
    "previousRole": "Food",
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId15,
    "firstName": "Aiden",
    "lastName": "Kim",
    "email": "aiden.kim@example.com",
    "phoneNumber": "1677654321",
    "address": "1212 Maple Drive, Lakeside, USA",
    "previousRole": "Save the Babies",
    "previousOrganization": organizationId8,
    "roleVerifications": [
      {
        "verifier": "Daniel Garcia",
        "lastUpdated": "2023-03-19T13:33:00Z",
        "role": "Save the Babies"
      }
    ],
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId16,
    "firstName": "Ava",
    "lastName": "Wilson",
    "email": "ava.wilson@example.com",
    "phoneNumber": "1567654321",
    "address": "1313 Birch Circle, Highland, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId5,
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-03-22T14:25:47Z"
    },
    "roleVerifications": [
      {
        "verifier": "Mia Davis",
        "lastUpdated": "2023-03-21T15:10:00Z",
        "role": "Medical"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId17,
    "firstName": "Oliver",
    "lastName": "Smith",
    "email": "oliver.smith@example.com",
    "phoneNumber": "1457654321",
    "address": "1414 Cedar Ave, Summit, USA",
    "previousRole": "Dental",
    "previousOrganization": organizationId7,
    "backgroundCheck": {
      "status": "Failed",
      "lastUpdated": "2023-03-05T20:20:20Z"
    },
    "roleVerifications": [
      {
        "verifier": "Alexander Wilson",
        "lastUpdated": "2023-03-04T18:30:00Z",
        "role": "Dental"
      },
      {
        "verifier": "Isabella Thomas",
        "lastUpdated": "2023-03-08T18:30:00Z",
        "role": "Save the Babies"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId18,
    "firstName": "Sophie",
    "lastName": "Nguyen",
    "email": "sophie.nguyen@example.com",
    "phoneNumber": "1347654321",
    "address": "1515 Oak St, Meadowview, USA",
    "previousRole": "Food",
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-03-08T21:10:40Z"
    },
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId19,
    "firstName": "William",
    "lastName": "Thompson",
    "email": "william.thompson@example.com",
    "phoneNumber": "1237654321",
    "address": "1616 Willow Way, Maplewood, USA",
    "previousOrganization": organizationId6,
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-03-11T22:30:00Z"
    },
    "roleVerifications": [
      {
        "verifier": "James Lee",
        "lastUpdated": "2023-03-10T20:40:00Z",
        "role": "Save the Babies"
      }
    ],
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId20,
    "firstName": "Zoe",
    "lastName": "Anderson",
    "email": "zoe.anderson@example.com",
    "phoneNumber": "1127654321",
    "address": "1717 Palm Road, Greenfield, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId7,
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-03-14T23:59:59Z"
    },
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId21,
    "firstName": "Lucas",
    "lastName": "Hernandez",
    "email": "lucas.hernandez@example.com",
    "phoneNumber": "1017654321",
    "address": "1818 Cherry St, Pinecrest, USA",
    "previousRole": "Dental",
    "previousOrganization": organizationId6,
    "backgroundCheck": {
      "status": "Failed",
      "lastUpdated": "2023-03-17T19:45:07Z"
    },
    "roleVerifications": [
      {
        "verifier": "Charlotte Anderson",
        "lastUpdated": "2023-03-16T22:30:00Z",
        "role": "Dental"
      }
    ],
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  }, 
  {
    "_id": volunteerId22,
    "firstName": "Ethan",
    "lastName": "Brown",
    "email": "ethan.brown@example.com",
    "phoneNumber": "2012345678",
    "address": "1919 Maple Avenue, Springtown, USA",
    "previousRole": "Food",
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-01T08:30:00Z"
    },
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId23,
    "firstName": "Emily",
    "lastName": "Davis",
    "email": "emily.davis@example.com",
    "phoneNumber": "2023456789",
    "address": "2020 Birchwood Road, Lakeville, USA",
    "previousRole": "Dental",
    "previousOrganization": organizationId2,
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-04-02T09:45:00Z"
    },
    "roleVerifications": [
      {
        "verifier": "Benjamin Nguyen",
        "lastUpdated": "2023-03-31T15:20:00Z",
        "role": "Dental"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId24,
    "firstName": "Olivia",
    "lastName": "Miller",
    "email": "olivia.miller@example.com",
    "phoneNumber": "2034567890",
    "address": "2121 Cedar Lane, Ridgewood, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId3,
    "backgroundCheck": {
      "status": "Failed",
      "lastUpdated": "2023-04-03T10:35:00Z"
    },
    "roleVerifications": [
      {
        "verifier": "Amelia Jackson",
        "lastUpdated": "2023-03-30T16:05:00Z",
        "role": "Food"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId25,
    "firstName": "James",
    "lastName": "Taylor",
    "email": "james.taylor@example.com",
    "phoneNumber": "2045678901",
    "address": "2222 Pine Street, Westview, USA",
    "previousRole": "Save the Babies",
    "previousOrganization": organizationId4,
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-04-04T12:00:00Z"
    },
    "roleVerifications": [
      {
        "verifier": "Henry Moore",
        "lastUpdated": "2023-04-03T17:30:00Z",
        "role": "Save the Babies"
      }
    ],
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId26,
    "firstName": "Grace",
    "lastName": "Wilson",
    "email": "grace.wilson@example.com",
    "phoneNumber": "2056789012",
    "address": "2333 Elm Street, Eastville, USA",
    "previousRole": "Medical",
    "previousOrganization": organizationId10,
    "roleVerifications": [
      {
        "verifier": "Harper Clark",
        "lastUpdated": "2023-04-04T18:45:00Z",
        "role": "Medical"
      }
    ],
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId27,
    "firstName": "Jackson",
    "lastName": "Martinez",
    "email": "jackson.martinez@example.com",
    "phoneNumber": "2067890123",
    "address": "2444 Oak Avenue, Northtown, USA",
    "previousRole": "Food",
    "backgroundCheck": {
      "status": "Failed",
      "lastUpdated": "2023-04-06T14:10:00Z"
    },
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId28,
    "firstName": "Amelia",
    "lastName": "Hernandez",
    "email": "amelia.hernandez@example.com",
    "phoneNumber": "2078901234",
    "address": "2555 Maple Court, Southtown, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId8,
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-07T15:20:00Z"
    },
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId29,
    "firstName": "Mia",
    "lastName": "Garcia",
    "email": "mia.garcia@example.com",
    "phoneNumber": "2089012345",
    "address": "2666 Walnut Street, Rivertown, USA",
    "previousRole": "Save the Babies",
    "backgroundCheck": {
      "status": "In Progress",
      "lastUpdated": "2023-04-08T16:30:00Z"
    },
    "roleVerifications": [
      {
        "verifier": "Jacob Baker",
        "lastUpdated": "2023-04-07T21:30:00Z",
        "role": "Save the Babies"
      }
    ],
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId30,
    "firstName": "Aiden",
    "lastName": "Robinson",
    "email": "aiden.robinson@example.com",
    "phoneNumber": "2090123456",
    "address": "2777 Birchwood Park, Creekview, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId1,
    "backgroundCheck": {
      "status": "Failed",
      "lastUpdated": "2023-04-09T17:45:00Z"
    },
    "softDelete": false,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_id": volunteerId31,
    "firstName": "Sophia",
    "lastName": "Lee",
    "email": "sophia.lee@example.com",
    "phoneNumber": "2101234567",
    "address": "2888 Cedarwood Road, Hillside, USA",
    "previousRole": "Food",
    "previousOrganization": organizationId1,
    "backgroundCheck": {
      "status": "Passed",
      "lastUpdated": "2023-04-10T18:50:00Z"
    },
    "softDelete": true,
    "createdAt": new Date(),
    "updatedAt": new Date()
  }
])

// creates 30 eventId variables
for (let i = 1; i <= 150; i++) {
  this[`eventId${i}`] = ObjectId();
}

// STANDALONE EVENTS
db.events.insertMany([
  {
    "_id": eventId1,
    "name": "Feast of Sharing",
    "description": "A day dedicated to sharing meals with the less fortunate.",
    "eventLocation": "Central Community Center",
    "startAt": new Date(ISODate().getTime() - 1000 * 3600 * 24 * 3 + 3600 * 3),
    "endAt": new Date(ISODate().getTime() - 1000 * 3600 * 24 * 3 + 3600 * 4),
    "date": new Date(ISODate().getTime() - 1000 * 3600 * 24 * 3),
    "eventRoles": ["Dental", "Food"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Feast of Sharing event on Friday, March 15, 2024 at Central Community Center. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": false
  },
  {
    "_id": eventId2,
    "name": "Health for All Fair",
    "description": "Providing free medical checkups and health education to the community.",
    "eventLocation": "Downtown Health Clinic",
    "startAt": new Date(ISODate().getTime() - 1000 * 3600 * 24 * 2 + 3600 * 7),
    "endAt": new Date(ISODate().getTime() - 1000 * 3600 * 24 * 3 + 3600 * 8.5),
    "date": new Date(ISODate().getTime() - 1000 * 3600 * 24 * 2),
    "eventRoles": ["Medical", "Dental", "Food", "Save the Babies"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Health for All Fair event on Thursday, May 02, 2024 at Downtown Health Clinic. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": false
  },
  {
    "_id": eventId3,
    "name": "Community Dental Day",
    "description": "Free dental checkups and oral health education for families.",
    "eventLocation": "Riverdale Park",
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3 + 3600 * 15),
    "endAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3 + 3600 * 18),
    "date": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3),
    "eventRoles": ["Save the Babies", "Medical", "Food"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Community Dental Day event on Friday, June 07, 2024 at Riverdale Park. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": false
  },
  {
    "_id": eventId4,
    "name": "Nutrition and Wellness Drive",
    "description": "Promoting nutrition and wellness through free workshops and food distribution.",
    "eventLocation": "Sunshine School Auditorium",
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 7 + 3600 * 20),
    "endAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * + 3600 * 20.5),
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 7),
    "eventRoles": ["Food"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Nutrition and Wellness Drive event on Saturday, July 21, 2024 at Sunshine School Auditorium. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": false
  },
  {
    "_id": eventId5,
    "name": "Hope Medical Camp",
    "description": "A medical camp offering various health services to underserved communities.",
    "eventLocation": "Green Valley Fairgrounds",
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.1 + 3600 * 18),
    "endAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.1 + 3600 * 21),
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.1),
    "eventRoles": ["Medical", "Save the Babies"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Hope Medical Camp event on Monday, August 12, 2024 at Green Valley Fairgrounds. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": false
  }
])

// RECURRING EVENT INSTANCES
db.events.insertMany([
  {
    "_id": eventId6,
    "name": "Food for Thought Evening",
    "description": "An evening event focused on discussing and distributing nutritious food.",
    "eventLocation": "Liberty Community Hall",
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.3),
    "endAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.3 + 3600 * 3),
    "eventRoles": ["Food", "Dental"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Food for Thought Evening event on Thursday, September 05, 2024 at Liberty Community Hall. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": true,
  },
  {
    "_id": eventId7,
    "name": "Smiles Dental Campaign",
    "description": "A campaign to offer dental services and promote oral hygiene.",
    "eventLocation": "Pinecrest Event Arena",
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.5),
    "endAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.5 + 3600 * 3),
    "eventRoles": ["Dental", "Medical"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Smiles Dental Campaign event on Wednesday, October 16, 2024 at Pinecrest Event Arena. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": true,
  },
  {
    "_id": eventId8,
    "name": "Harvest of Health Expo",
    "description": "An expo offering health screenings, wellness workshops, and more.",
    "eventLocation": "Oceanview Pavilion",
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.5),
    "endAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.5 + 3600 * 3),
    "eventRoles": ["Dental"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Harvest of Health Expo event on Friday, June 28, 2024 at Oceanview Pavilion. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": true,
  },
  {
    "_id": eventId9,
    "name": "Well-being and Care Fest",
    "description": "A festival celebrating health care workers and offering community health services.",
    "eventLocation": "Mountainview Conference Center",
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.7),
    "endAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.7 + 3600 * 3),
    "eventRoles": ["Medical", "Save the Babies"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Well-being and Care Fest event on Sunday, November 10, 2024 at Mountainview Conference Center. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": true,
  },
  {
    "_id": eventId10,
    "name": "Nourish to Flourish Initiative",
    "description": "An initiative to provide nourishing meals and nutrition education to those in need.",
    "eventLocation": "Lakeside Retreat",
    "startAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.9),
    "endAt": new Date(ISODate().getTime() + 1000 * 3600 * 24 * 3.9 + 3600 * 3),
    "eventRoles": ["Medical"],
    "emailBodies": [
      "Dear Volunteer, thank you for your hard work during the Nourish to Flourish Initiative event on Sunday, September 29, 2024 at Lakeside Retreat. Your efforts made a significant difference. We hope to see you again soon at our upcoming events.",
      "Stay tuned for more opportunities to make a difference in your community with our future volunteering events. Your support is invaluable to us."
    ],
    "isRecurring": true,
  }
])

// creates 150 eventVolunteerId variables
for (let i = 1; i <= 150; i++) {
  this[`eventVolunteerId${i}`] = ObjectId();
}

db.eventVolunteers.insertMany([
    {
        "_id": eventVolunteerId1,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId7,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId2,
        "role": "Medical",
        "organization": organizationId4,
        "volunteer": volunteerId5,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId3,
        "role": "Food",
        "organization": organizationId10,
        "volunteer": volunteerId14,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId4,
        "role": "Food",
        "volunteer": volunteerId2,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId5,
        "role": "Food",
        "organization": organizationId3,
        "volunteer": volunteerId8,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId6,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId31,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId7,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId3,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId8,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId9,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId10,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId10,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId11,
        "role": "Dental",
        "organization": organizationId2,
        "volunteer": volunteerId23,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId12,
        "role": "Dental",
        "organization": organizationId8,
        "volunteer": volunteerId23,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId13,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId12,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId14,
        "role": "Food",
        "organization": organizationId4,
        "volunteer": volunteerId11,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId15,
        "role": "Dental",
        "organization": organizationId2,
        "volunteer": volunteerId19,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId16,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId27,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId17,
        "role": "Food",
        "organization": organizationId7,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId18,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId7,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId19,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId3,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId20,
        "role": "Food",
        "organization": organizationId7,
        "volunteer": volunteerId2,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId21,
        "role": "Food",
        "organization": organizationId3,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId22,
        "role": "Medical",
        "organization": organizationId2,
        "volunteer": volunteerId1,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId23,
        "role": "Food",
        "organization": organizationId4,
        "volunteer": volunteerId13,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId24,
        "role": "Food",
        "organization": organizationId10,
        "volunteer": volunteerId28,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId25,
        "role": "Medical",
        "organization": organizationId1,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId26,
        "role": "Save the Babies",
        "organization": organizationId6,
        "volunteer": volunteerId15,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId27,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId7,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId28,
        "role": "Food",
        "volunteer": volunteerId22,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId29,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId15,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId30,
        "role": "Save the Babies",
        "organization": organizationId3,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId31,
        "role": "Food",
        "organization": organizationId7,
        "volunteer": volunteerId28,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId32,
        "role": "Save the Babies",
        "organization": organizationId6,
        "volunteer": volunteerId8,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId33,
        "role": "Food",
        "organization": organizationId3,
        "volunteer": volunteerId23,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId34,
        "role": "Food",
        "organization": organizationId4,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId35,
        "role": "Food",
        "organization": organizationId4,
        "volunteer": volunteerId11,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId36,
        "role": "Food",
        "organization": organizationId10,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId37,
        "role": "Dental",
        "organization": organizationId6,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId38,
        "role": "Food",
        "organization": organizationId10,
        "volunteer": volunteerId14,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId39,
        "role": "Save the Babies",
        "organization": organizationId7,
        "volunteer": volunteerId8,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId40,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId12,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId41,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId2,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId42,
        "role": "Save the Babies",
        "organization": organizationId7,
        "volunteer": volunteerId17,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId43,
        "role": "Medical",
        "organization": organizationId8,
        "volunteer": volunteerId12,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId44,
        "role": "Dental",
        "organization": organizationId4,
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId45,
        "role": "Food",
        "organization": organizationId4,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId46,
        "role": "Dental",
        "organization": organizationId1,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId47,
        "role": "Dental",
        "organization": organizationId5,
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId48,
        "role": "Medical",
        "organization": organizationId5,
        "volunteer": volunteerId5,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId49,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId24,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId50,
        "role": "Medical",
        "organization": organizationId6,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId51,
        "role": "Save the Babies",
        "organization": organizationId1,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId52,
        "role": "Dental",
        "organization": organizationId4,
        "volunteer": volunteerId23,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId53,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId54,
        "role": "Save the Babies",
        "organization": organizationId1,
        "volunteer": volunteerId19,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId55,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId56,
        "role": "Food",
        "organization": organizationId7,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId57,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId1,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId58,
        "role": "Medical",
        "organization": organizationId3,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId59,
        "role": "Food",
        "organization": organizationId5,
        "volunteer": volunteerId22,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId60,
        "role": "Medical",
        "organization": organizationId10,
        "volunteer": volunteerId9,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId61,
        "role": "Save the Babies",
        "organization": organizationId10,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId62,
        "role": "Food",
        "organization": organizationId5,
        "volunteer": volunteerId9,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId63,
        "role": "Food",
        "organization": organizationId7,
        "volunteer": volunteerId14,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId64,
        "role": "Food",
        "volunteer": volunteerId8,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId65,
        "role": "Save the Babies",
        "organization": organizationId5,
        "volunteer": volunteerId15,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId66,
        "role": "Food",
        "organization": organizationId5,
        "volunteer": volunteerId7,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId67,
        "role": "Save the Babies",
        "organization": organizationId2,
        "volunteer": volunteerId14,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId68,
        "role": "Medical",
        "organization": organizationId8,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId69,
        "role": "Food",
        "organization": organizationId7,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId70,
        "role": "Food",
        "organization": organizationId3,
        "volunteer": volunteerId24,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId71,
        "role": "Save the Babies",
        "organization": organizationId7,
        "volunteer": volunteerId17,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId72,
        "role": "Save the Babies",
        "organization": organizationId7,
        "volunteer": volunteerId15,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId73,
        "role": "Dental",
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId74,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId75,
        "role": "Food",
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId76,
        "role": "Medical",
        "organization": organizationId7,
        "volunteer": volunteerId12,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId77,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId12,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId78,
        "role": "Save the Babies",
        "organization": organizationId1,
        "volunteer": volunteerId15,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId79,
        "role": "Food",
        "organization": organizationId10,
        "volunteer": volunteerId25,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId80,
        "role": "Food",
        "organization": organizationId5,
        "volunteer": volunteerId31,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId81,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId82,
        "role": "Food",
        "organization": organizationId10,
        "volunteer": volunteerId18,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId83,
        "role": "Food",
        "organization": organizationId7,
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId84,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId85,
        "role": "Dental",
        "organization": organizationId10,
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId86,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId24,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId87,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId1,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId88,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId89,
        "role": "Medical",
        "organization": organizationId4,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId90,
        "role": "Medical",
        "organization": organizationId2,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId91,
        "role": "Food",
        "organization": organizationId4,
        "volunteer": volunteerId28,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId92,
        "role": "Dental",
        "volunteer": volunteerId17,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId93,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId15,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId94,
        "role": "Medical",
        "organization": organizationId4,
        "volunteer": volunteerId1,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId95,
        "role": "Dental",
        "organization": organizationId3,
        "volunteer": volunteerId23,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId96,
        "role": "Dental",
        "organization": organizationId3,
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId97,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId22,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId98,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId2,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId99,
        "role": "Dental",
        "organization": organizationId4,
        "volunteer": volunteerId6,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId100,
        "role": "Food",
        "organization": organizationId4,
        "volunteer": volunteerId5,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId101,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId7,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId102,
        "role": "Food",
        "volunteer": volunteerId5,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId103,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId9,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId104,
        "role": "Food",
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId105,
        "role": "Dental",
        "organization": organizationId4,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId106,
        "role": "Save the Babies",
        "organization": organizationId10,
        "volunteer": volunteerId8,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId107,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId5,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId108,
        "role": "Food",
        "organization": organizationId5,
        "volunteer": volunteerId27,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId109,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId110,
        "role": "Save the Babies",
        "organization": organizationId6,
        "volunteer": volunteerId8,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId111,
        "role": "Medical",
        "organization": organizationId2,
        "volunteer": volunteerId1,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId112,
        "role": "Medical",
        "organization": organizationId3,
        "volunteer": volunteerId9,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId113,
        "role": "Save the Babies",
        "organization": organizationId6,
        "volunteer": volunteerId17,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId114,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId115,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId8,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId116,
        "role": "Medical",
        "organization": organizationId10,
        "volunteer": volunteerId5,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId117,
        "role": "Dental",
        "organization": organizationId10,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId118,
        "role": "Food",
        "volunteer": volunteerId10,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId119,
        "role": "Save the Babies",
        "organization": organizationId3,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId120,
        "role": "Save the Babies",
        "organization": organizationId3,
        "volunteer": volunteerId17,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId121,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId122,
        "role": "Medical",
        "organization": organizationId1,
        "volunteer": volunteerId9,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId123,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId18,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId124,
        "role": "Food",
        "volunteer": volunteerId16,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId125,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId15,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId126,
        "role": "Save the Babies",
        "organization": organizationId8,
        "volunteer": volunteerId4,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId127,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId26,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId128,
        "role": "Medical",
        "volunteer": volunteerId12,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId129,
        "role": "Food",
        "volunteer": volunteerId14,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId130,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId24,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId131,
        "role": "Dental",
        "organization": organizationId3,
        "volunteer": volunteerId21,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId132,
        "role": "Food",
        "organization": organizationId3,
        "volunteer": volunteerId13,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId133,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId13,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId134,
        "role": "Dental",
        "organization": organizationId1,
        "volunteer": volunteerId17,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId135,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId25,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId136,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId5,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId137,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId20,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId138,
        "role": "Food",
        "organization": organizationId8,
        "volunteer": volunteerId7,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId139,
        "role": "Food",
        "organization": organizationId3,
        "volunteer": volunteerId17,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId140,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId15,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId141,
        "role": "Food",
        "organization": organizationId1,
        "volunteer": volunteerId30,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId142,
        "role": "Save the Babies",
        "organization": organizationId5,
        "volunteer": volunteerId19,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId143,
        "role": "Dental",
        "organization": organizationId6,
        "volunteer": volunteerId17,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId144,
        "role": "Medical",
        "organization": organizationId5,
        "volunteer": volunteerId1,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId145,
        "role": "Medical",
        "volunteer": volunteerId12,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId146,
        "role": "Medical",
        "organization": organizationId1,
        "volunteer": volunteerId12,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId147,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId14,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId148,
        "role": "Food",
        "volunteer": volunteerId11,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId149,
        "role": "Food",
        "organization": organizationId6,
        "volunteer": volunteerId24,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
    {
        "_id": eventVolunteerId150,
        "role": "Food",
        "organization": organizationId2,
        "volunteer": volunteerId10,
        "event": ObjectId(),
        "createdAt": new Date(),
        "updatedAt": new Date()
    },
])

